# This updates the json file containing documentation errors every hour. 
# Based on: https://github.com/pandas-dev/pandas/blob/master/.github/workflows/ci.yml

name: update_json

# Runs the update every hour
on:
  schedule:
    - cron: '0 * * * *'

env:
  ENV_FILE: environment.yml

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    
    - name: Setting conda path
      run: echo "::add-path::${HOME}/miniconda3/bin"
      
    - name: Chekout pandas-dev
      uses: actions/checkout@v2
      with:
        repository: pandas-dev/pandas
        
    - name: Setup environment and build pandas
      run: ci/setup_env.sh
      if: always()
    
    - name: Run docstring (test)
      run: |
        source activate pandas-dev
        echo "$HOME"

